server:
  port: 80
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_diancan?serverTimezone=Asia/Shanghai
    username: root
    password: zql123456

mybatis-plus:
  global-config:
    db-config:
      id-type: auto #id生成规则：数据库id自增
  configuration:
    map-underscore-to-camel-case: false
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*.xml

weixin:
  accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token
  appid: wxd6aa2b8ebc8382ab
  secret: fbebc76bb2d1009d0be5662e9d54fe89

qrcodeImgsFilePath: ./users/diancan/qrcodeImgs/
dishImgsFilePath:  ./users/diancan/dishImgs/